version: "3"

services:
  frontend:
    container_name: jdi_frontend
    build: ../just_do_it
    env_file: ../just_do_it/.env.development
    volumes:
      - ../just_do_it:/app
    ports:
      - "3000:3000"

  backend:
    container_name: jdi_backend
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"

  postgres:
    container_name: jdi_postgres
    image: postgres
    ports:
      - "5433:5432"
    env_file: .development.env
    volumes:
      - ~/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin


