version: "3"

services:
  frontend:
    container_name: jdi_frontend
    build: ../just_do_it
    volumes:
      - ../just_do_it:/app
    ports:
      - "3000:3000"

  backend:
    container_name: jdi_backend
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"


